# Generated by Django 3.2.23 on 2023-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='products'),
        ),
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='products'),
        ),
    ]
